[package]
name = "barcode-scanner-http-client"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
evdev = "0.13.2"
reqwest = "0.12.24"
tokio = { version = "1.48.0", features = ["full"] }
